# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master


jobs:

- template: ci/azure/posix.yml
  parameters:
    name: Test_bare_Linux
    vmImage: ubuntu-16.04


- template: ci/azure/posix.yml
  parameters:
    name: Test_bare_macOS
    vmImage: macOS-10.14


- template: ci/azure/conda_linux.yml
  parameters:
    name: Test_conda_linux
    vmImage: ubuntu-16.04


- template: ci/azure/conda_windows.yml
  parameters:
    name: Test_conda_windows
    vmImage: vs2017-win2016


- job: 'Publish'
  dependsOn: 'Test_conda_linux'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'

  - script: python setup.py sdist
    displayName: 'Build sdist'
